In [4]:
import pandas as pd
DF_COLUMNS = ['User ID',
            'Venue ID',
            'Venue Category ID',
            'Venue Category Name',
            'Latitude',
            'Longitude',
            'Timezone Offset',
            'UTC Time']
df = pd.read_csv('data/FNYC/raw_files/dataset_tsmc2014/dataset_TSMC2014_NYC.txt',  sep='\t', encoding='latin-1', names=DF_COLUMNS)
df = df.sort_values(by=['User ID'])
df = df.drop_duplicates()
df.shape[0]

227178

In [7]:

def collect_unique_venue_locations(dataframe):
    """
    Collect all different locations assigned to each unique venue across all records.

    Args:
        dataframe (pd.DataFrame): The input dataframe with venue check-in data.

    Returns:
        dict: A dictionary where keys are Venue IDs and values are lists of unique locations (latitude, longitude).
    """
    # Group by 'Venue ID' and aggregate unique locations (Latitude, Longitude)
    venue_locations = (
        dataframe.groupby('Venue ID', group_keys=False)
        .apply(lambda group: group[['Latitude', 'Longitude']].drop_duplicates().reset_index(drop=True).values.tolist())
        .to_dict()
    )
    return venue_locations

# Example usage
unique_venue_locations = collect_unique_venue_locations(df)

# Display venues with multiple locations (if any)
venues_with_multiple_locations = {venue: locations for venue, locations in unique_venue_locations.items() if len(locations) > 1}

print(len(venues_with_multiple_locations))

3484


/tmp/ipykernel_1306831/2144088096.py:14: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda group: group[['Latitude', 'Longitude']].drop_duplicates().reset_index(drop=True).values.tolist())


In [14]:
from itertools import combinations
from math import radians, sin, cos, sqrt, atan2

def collect_unique_venue_locations(dataframe):
    """
    Collect all different locations assigned to each unique venue across all records.

    Args:
        dataframe (pd.DataFrame): The input dataframe with venue check-in data.

    Returns:
        dict: A dictionary where keys are Venue IDs and values are lists of unique locations (latitude, longitude).
    """
    # Group by 'Venue ID' and aggregate unique locations (Latitude, Longitude)
    venue_locations = (
        dataframe.groupby('Venue ID')
        .apply(lambda group: group[['Latitude', 'Longitude']].drop_duplicates().values.tolist())
        .to_dict()
    )
    return venue_locations

def haversine_distance(loc1, loc2):
    """
    Calculate the great-circle distance between two points on the Earth using the Haversine formula.

    Args:
        loc1 (tuple): (latitude, longitude) of the first location in decimal degrees.
        loc2 (tuple): (latitude, longitude) of the second location in decimal degrees.

    Returns:
        float: Distance between the two points in kilometers.
    """
    # Radius of the Earth in kilometers
    R = 6371.0

    # Convert latitude and longitude from degrees to radians
    lat1, lon1 = radians(loc1[0]), radians(loc1[1])
    lat2, lon2 = radians(loc2[0]), radians(loc2[1])

    # Differences in coordinates
    dlat = lat2 - lat1
    dlon = lon2 - lon1

    # Haversine formula
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    # Distance
    return R * c * 1000

def calculate_longest_distance(venue_locations):
    """
    Calculate the longest great-circle distance between different locations assigned to each unique venue.

    Args:
        venue_locations (dict): A dictionary where keys are Venue IDs and values are lists of unique locations (latitude, longitude).

    Returns:
        dict: A dictionary where keys are Venue IDs and values are the longest great-circle distance (if more than one location exists).
    """
    longest_distances = {}

    for venue, locations in venue_locations.items():
        if len(locations) > 1:
            # Calculate all pairwise distances using the Haversine formula
            distances = [haversine_distance(loc1, loc2) for loc1, loc2 in combinations(locations, 2)]
            longest_distances[venue] = max(distances)
        else:
            longest_distances[venue] = 0  # No distance if only one location

    return longest_distances

def get_sorted_venues_by_distance(longest_distances):
    """
    Sort venues by their longest distances in descending order.

    Args:
        longest_distances (dict): A dictionary where keys are Venue IDs and values are the longest Euclidean distances.

    Returns:
        list: A list of tuples sorted by longest distance in descending order (Venue ID, Longest Distance).
    """
    return sorted(longest_distances.items(), key=lambda x: x[1], reverse=True)

# Example usage
unique_venue_locations = collect_unique_venue_locations(df)
longest_distances = calculate_longest_distance(unique_venue_locations)
sorted_venues = get_sorted_venues_by_distance(longest_distances)

/tmp/ipykernel_1306831/2553799605.py:17: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda group: group[['Latitude', 'Longitude']].drop_duplicates().values.tolist())


In [15]:
i = 0
for venue, distance in sorted_venues:
    print(venue, distance)
    i+=1
    if i == 10:
        break

4ddad40bd22d4dbc8c0d4f91 20875.184303474245
4be2144d21d5a59302ca1511 19864.869301420516
4f386335e4b08f009a8525de 16384.124820247493
4c7170dafa49a1cd60e6a8e3 15937.920618432663
4a8c0960f964a520e50c20e3 14393.90774926774
4f1708fae4b0044a28cbe14f 11763.24908652051
4e0e0b3caeb7a5b33ee5dac1 7748.079960620895
4e7b9f93b61c001c6b38f13f 7233.508154016825
4e51dcc76284416669b03aec 6345.832450303119
4dc7d9d81f6ef43b8a4e609a 5353.036771362292


In [1]:
!python train.py

Dataset already downloaded!
Dataset already extracted!
Dateset statistics before filtering:
Number of users: 1083, with min = 100, max = 2693, and avg: 209.76731301939057
Number of venues: 38333, with min = 1, max = 1145, and avg: 5.926434142905591
Number of venue categories: 400
Dateset statistics after filtering:
Number of users: 1081, with min = 20, max = 2511, and avg: 136.6096207215541
Number of venues: 5128, with min = 10, max = 1145, and avg: 28.797776911076443
Number of venue categories: 320
Spatial graph sparsity: 0.9934740076810561
Temporal graph sparsity: 0.9182665190772997
/home/mosix11/Projects/DL/dlpenv/lib/python3.10/site-packages/torch/nn/modules/rnn.py:123: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 -

In [1]:
from src.dataset import FoursquareNYC
from src.models import TrajLSTM

ds = FoursquareNYC(batch_size=8, num_workers=1)
ds.setup('fit')
ds.setup('test')
# model = TrajLSTM(num_user=ds.STATS['num_user'],
#                  num_pois=ds.STATS['num_pois'])

Dataset already downloaded!
Dataset already extracted!
Dateset statistics before filtering:
Number of records: 227178
Number of users: 1083, with min = 100, max = 2693, and avg: 209.76731301939057
Number of venues: 38333, with min = 1, max = 1145, and avg: 5.926434142905591
Number of venue categories: 400
Dateset statistics after filtering:
Number of records: 147675
Number of users: 1081, with min = 20, max = 2511, and avg: 136.6096207215541
Number of venues: 5128, with min = 10, max = 1145, and avg: 28.797776911076443
Number of venue categories: 320
Spatial graph sparsity: 99.3473171064128
Temporal graph sparsity: 91.82665190772997


In [19]:
spatial_graph = ds.spatial_graph
temporal_graph = ds.temporal_graph

print(spatial_graph.shape)
print(temporal_graph.shape)

torch.Size([5129, 5129])
torch.Size([5129, 5129])


In [35]:
import torch
dl_train = ds.train_dataloader()
dl_test = ds.test_dataloader()
batch = next(iter(dl_train))
x, y, lens = batch
pois = x[1]
seq_len = pois.size(1)
mask = torch.arange(seq_len).expand(
            len(lens), seq_len
        ) < lens.unsqueeze(1)


In [3]:
model = TrajLSTM(ds)

In [42]:
print(lens)

print(pois[-2])
print(y[1][-2])
print(mask[-2])

tensor([63, 63, 53, 63, 63, 63, 52, 63])
tensor([3069,  989,  595, 4240, 4240, 4240, 4240,  989, 4240,  989,  989, 4240,
        4240, 4240, 4241, 4240, 4240,  595, 4240, 4241, 4240, 4240, 4241, 4240,
         595, 4240, 4241, 4240,  989, 4241, 4240,  989,  224,  339,   38, 4241,
        4240, 4241, 4240, 4240, 4241, 4240,  989, 4240, 4240, 4241,  195,  989,
        4240, 4241,    9, 4241,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0])
tensor([ 989,  595, 4240, 4240, 4240, 4240,  989, 4240,  989,  989, 4240, 4240,
        4240, 4241, 4240, 4240,  595, 4240, 4241, 4240, 4240, 4241, 4240,  595,
        4240, 4241, 4240,  989, 4241, 4240,  989,  224,  339,   38, 4241, 4240,
        4241, 4240, 4240, 4241, 4240,  989, 4240, 4240, 4241,  195,  989, 4240,
        4241,    9, 4241, 4240,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0])
tensor([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True

In [55]:
neighbors = spatial_graph[pois]  # shape: (batch_size, seq_len, num_nodes)
masked_neighbors = neighbors * mask.unsqueeze(-1)
print(torch.equal(neighbors, masked_neighbors))
nonzero_indices = torch.nonzero(spatial_graph[4241], as_tuple=True)[0]
print(nonzero_indices)
nonzero_indices = torch.nonzero(neighbors[-2][-1], as_tuple=True)[0]
print(nonzero_indices)
print(torch.sum(spatial_graph[0, :]))
# print(neighbors.shape)
# print(mask)

True
tensor([3827, 3828, 3829, 4240, 4241, 4934, 5050])
tensor([], dtype=torch.int64)
tensor(0)


In [60]:
neighbors = spatial_graph[pois]  # shape: (batch_size, seq_len, num_nodes)
masked_neighbors = neighbors * mask.unsqueeze(-1)
print(torch.equal(neighbors, masked_neighbors))
nonzero_indices = torch.nonzero(spatial_graph[4241])[0]
print(nonzero_indices)
nonzero_indices = torch.nonzero(masked_neighbors[-2][-12])[0]
print(nonzero_indices)

True
torch.Size([7, 1])
tensor([3827, 3828, 3829, 4240, 4241, 4934, 5050])


In [2]:
ds.STATS

{'num_user': 1081,
 'num_pois': 5128,
 'num_poi_cat': 320,
 'num_time_slots': 56,
 'num_gh_P5': 114,
 'num_gh_P6': 1120,
 'num_gh_P7': 3087}

In [19]:
s = 0
mdict = ds.hierarchical_spatial_graph['P5_to_P6']

for key, value in mdict.items():
    s += len(value)
print(s)

1120


In [ ]:
import ipywidgets as widgets
import numpy as np
import torch
from IPython.display import display
widget = widgets.Output()
# with widget:
#     display(ds.poi_trajectories)
# print(ds.user_train_trajectories.iloc[400])
ds.setup(stage='fit')
ds.setup(stage='test')
dl_train = ds.train_dataloader()
dl_test = ds.test_dataloader()
x, y, lens = next(iter(dl_train)) 
user_ids = x[0]
pois = x[1]
seq_len = pois.size(1)
mask = torch.arange(seq_len).expand(len(lens), seq_len) < lens.unsqueeze(1)
expanded_user_ids = user_ids.unsqueeze(1).repeat(1, pois.size(1))
print(lens)
print(expanded_user_ids.shape)
print(pois.shape)
# print(expanded_user_ids.shape)
print(expanded_user_ids * mask)
# print(pois.shape)
# print(y[1][0])
# print(y[1].reshape(-1))
# print(lens)
# print(x[1].shape)
# print(next(iter(dl_test)))
# for batch in dl_test:
#     pass

# display(widget)

# lengths1 = np.array(ds.user_train_trajectories['Time Slot'].apply(len))
# lengths2 = np.array(ds.user_train_trajectories['Venue ID'].apply(len))
# lengths3 = np.array(ds.user_train_trajectories['Geohash ID'].apply(len))

# ds.plot_distribution(lengths)
